web/myapp/API/urls.py
from django.urls import path, include
from django.contrib import admin

from . import views

app_name = 'API'
urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('test_request/', views.test_request, name='test_request'),
    path('test_response/', views.test_response, name='test_response'),
    path('inference/', views.inference, name='inference'),
    path('post/', views.post_api, name='post'),
    path('get/', views.get_api, name='get'),
    path('post_history/', views.post_history, name='post_history'),
    path('get_my_data/', views.get_my_data, name='get_my_data'),
    path('test_create_data/', views.test_create_data, name='test_create_data'),
    path('tag_update', views.tag_update, name='tag_update'),
    path('check_bookmark', views.check_bookmark, name='check_bookmark'),
    path('remove_bookmark/', views.remove_bookmark, name='remove_bookmark'),
]

web/myapp/SERVICE/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'SERVICE'
urlpatterns = [
    path('', views.index, name='index'),
    path('test_for_search/', views.search_tags, name='search_tags'),
    path('user_info/', views.user_info, name='user_info'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web/myapp/myapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('SERVICE/', include('SERVICE.urls', namespace='SERVICE')),
    path('API/', include('API.urls', namespace='API')),
    path('admin/', admin.site.urls),
]

web/myapp/SERVICE/models.py
from django.db import models

# Create your models here.

web/myapp/SERVICE/views.py
import json
import logging

from django.urls import reverse
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.contrib.sessions.models import Session
from django.core.serializers.json import DjangoJSONEncoder
from rest_framework.decorators import api_view
from rest_framework import status
from API.models import UserInfo, Bookmarks, Bookmark, Bookmark_Of_Customer

logger = logging.getLogger(__name__)

@api_view(['GET'])
def index(request):
    if request.method == 'GET':
    
        host_url = request.get_host()
        redirect_url = reverse('API:get_my_data')
        full_redirect_url = f"http://{host_url}{redirect_url}"
        
        try: 
            if request.session['update']:
                request.session['update'] = False
                
                user_bookmark = request.session['my_data']  # response 형식의 데이터를 return
                user_bookmark_json = json.dumps(user_bookmark, cls=DjangoJSONEncoder)
                customer_id = request.session['customer_id']
                context = {
                    'user_bookmark_json': user_bookmark_json,
                    'customer_id': customer_id,
                }
                
                return render(request, 'SERVICE/index.html', context) 
            
            else:
                return redirect(full_redirect_url)
            
        except KeyError:
            return redirect(full_redirect_url)
    
    else:
        logger.error("[ERROR] Illegal request is requested.")
        return JsonResponse({'success': False}, status=status.HTTP_405_METHOD_NOT_ALLOWED)


@api_view(['POST'])
def user_info(request):
    if request.method == 'POST':
        print("GET in user_info requested!")
        data = json.loads(request.body.decode('utf-8'))
        
        suser_id = data['customer_id']
        suser_email = data['userEmail']
        request.session['customer_id'] = data['customer_id']
        request.session['userEmail'] = data['userEmail']
        
        print(suser_id, suser_email)
        
        return JsonResponse({'success': True})
    

@api_view(['POST', 'GET'])
def search_tags(request):
    # new tab에서 검색하고자 하는 키워드에 대한 함수
    if request.method == 'POST':
        # input 처리
        input_data = request.POST.get('tag')
        print("User request, tag: ", input_data)
        
        # 0. 유저 정보 획득
        # 1. 해당 유저의 북마크만 검색
        # 2. 입력된 값을 타이틀, 태그에서 검색
        # 3. 결과 출력
        
        # 유저 정보 획득: 새 탭이 열릴때 획득.
        
        ####
        # input_data split
        input_tags = [tag.strip() for tag in input_data.split(',') if tag.strip()]
        print("input_tags: ", input_tags)
        # 유저 북마크 정보만 검색
        suser = Bookmark_Of_Customer.objects.filter(customer_id=request.session['customer_id'])
        
        # 이제 여기서 북마크 정보들을 가지고, Bookmark에서 필터링이 필요.
        suser_bookmark = Bookmark.objects.filter(no__in=suser)
        suser_bookmark_with_tags = suser_bookmark.filter(tags__icontains=input_tags[0])

        print("suser: ", suser)
        print("suser_bookmark: ", suser_bookmark)
        print("suser_bookmark_with_tags: ", suser_bookmark_with_tags)
        
        return_url = [[item.url] for item in suser_bookmark_with_tags]
        return_tags = [[item.tags] for item in suser_bookmark_with_tags]
        print("tags: ", return_tags)
        filtered_data = {item.url:item.tags for item in suser_bookmark_with_tags}

        print("filtered_data: ", filtered_data)
        
        return render(request, 'test_for_search.html', {'filtered_data': filtered_data})
        # return JsonResponse({'success': True}, status=200)
    
    # new tab을 띄우라는 크롬 익스텐션의 요청에 따른 함수
    elif request.method == 'GET':
        print("get is requested!")
        # Handle the GET request
        # Add any necessary logic or processing here
        
        # Return a response
        response_data = {'message': 'This is a GET request'}
        return render(request, 'test_for_search.html')
    
    else:
        return JsonResponse(status=400)

web/myapp/SERVICE/templates/SERVICE/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter&display=swap" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,-25" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined">
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+KR:wght@300&family=Orbit&display=swap" rel="stylesheet">

    <!-- jQuery UI CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />

    <!-- jQuery and jQuery UI JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

    <title>Service Page</title>

    <script>
      var userBookmark = JSON.parse('{{ user_bookmark_json | escapejs }}');
      var customer_id = '{{ customer_id | escapejs}}';
      var SERVER_URL = "{% url 'API:tag_update' %}";
    </script>

    <style>
        textarea {
          font-size: 3px;
        }
        table {
          width: 100%;
        }
        th {
          padding: 10px; /* 원하는 간격으로 조정 */
        }
    </style>
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">
</head>
<body>
    <div class="header">
      <img class='img' src="{% static 'image/Logo.png' %}">
    </div>

      <div class="container">
        <div class="Favorites">
          <div class="f_tmp"></div>
          <button id="f_add">&#43;</button>
          <!-- <div class="f2"></div> -->
          <!-- <div class="f3"></div> -->
          <div class="Refresh">&#11118;</div>
        </div>
        <div class="content1", id="content1">
          <!-- <div class="flexible-textbox"></div> -->
          <!-- <label for="site-search">Search the tag:</label> -->
          <div class='search_tag'>
            <input 
              type="text" style="font-family: 'Noto Sans KR', sans-serif;" class="flexible-textbox" id = 'input-tag' placeholder="  검색할 태그를 입력해 주세요: 형식은 #tag" 
            />
          </div>
          <!-- <img src="https://s3.ap-northeast-2.amazonaws.com/cdn.wecode.co.kr/icon/search.png"> -->
          <!-- <button><span class="material-symbols-outlined">manage_search</span></button></button> -->
          <div id="tags"></div>
  
        </div>  
        <div class="content2">
            <div class="tag_box_current">
                <div id="selected-tags"></div>
            </div>    
        </div>  
  
        <div class="content3">
          <div class="url_box" >

            <table>
              <thead>
                  <tr>
                      <th>제목</th>
                      <th>태그</th>
                      <!-- <th>Tags_block</th> -->
                      <th>수정</th>
                      <th>삭제</th>
                  </tr>
              </thead>
              <tbody id="bookmarks_whole"> </tbody>
            </table>

          </div>
  
        </div>  
       
      </div>
      <!-- Modal -->
      <div id="myModal" class="modal" style="display:hidden">
        <!-- <div class="modal-title">Add label name</div> -->
        <div class="modal-content">
          <div id="bookmark-info">
            <!-- 북마크 정보를 여기에 동적으로 추가할 예정 -->
          </div>
          <span class="close">&times;</span>
          <!-- Content of the modal goes here -->
        </div>
        
      </div>

      <!-- Modal -->
      <div id="favoriteModal" class="modal" style="display:hidden;">
        <!-- <div class="modal-title">Add label name</div> -->
        <div class="modal-content-f">
          
          <span class="close">&times;</span>
          <div id="modalContent"></div>
          <!-- Content of the modal goes here -->
        </div>
        
      </div>
  
      {% comment %} <div class="footer">
        <div id="tag-output"></div>
      </div> {% endcomment %}

</body>
</html>